### PR TITLE
Add an example for patching methods with pagination

### PR DESCRIPTION
**Pull request by aidistan**
This PR proposes an example for patching methods with pagination.

And it would be better to support paginations natively.

### CODE REVIEW

**Comment by mgmarlow** [comment]
Hello again! Thanks for taking the time to write this up. I'm not sure if I agree on including this example with the project, as I don't want to recommend that users of the gem monkey-patch modules that are considered part of the gem's private API. In other words, I don't want to cause bugs by changing the names or namespaces of these modules :)

**Comment by aidistan** [comment]
I have done researches on ruby gems for Notion APIs and found this gem my favorite. However for my own experience, supporting cursor pagination is a must-have feature which has been implemented in other competitors such as [`notion-ruby-client`](https://github.com/orbit-love/notion-ruby-client#pagination).

Thus I wrote these patches in a DRY way for my own project alongside others irrelated to this gem such as `Notion::Block#to_md` 😄 

This PR is just a proposal to supporting the feature, either by providing an example, or, in a preferable way, implementing methods with pagniations natively in the gem.

**Comment by mgmarlow** [comment]
Agreed, it would be nice to have the SDK assist with pagination, at least when it comes down to handling retries and respectfully querying the Notion APIs.

This is definitely something the SDK should implement, so I've opened up #12 to address it.

**Comment by aidistan** [comment]
Glad the idea proposed here has been addressed in a far more delicate way (#12). Hope it get closed soon.

I see no point to keep this PR, thus decide to close it.

**Pull request closed without merging**
